# This file stores configurations for your Shopify app.

client_id = "c294c7deee4ccc6e07d8acdf83e681ed"
application_url = "https://simple-qr-generator.pfplapp.com/"
embedded = true
name = "Qgen"
handle = "qr-generator"

[build]
automatically_update_urls_on_dev = true
dev_store_url = "quickstart-e95546ec.myshopify.com"
include_config_on_deploy = true

[auth]
redirect_urls = [
  "https://simple-qr-generator.pfplapp.com/auth/callback",
  "https://simple-qr-generator.pfplapp.com/auth/shopify/callback",
  "https://simple-qr-generator.pfplapp.com/api/auth/callback",
  "https://simple-qr-generator.pfplapp.com/api/auth/oauth/callback",
]

scopes = "write_products,read_products"

[webhooks]
api_version = "2024-10"

  # Handled by: /app/routes/webhooks.app.uninstalled.tsx
  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = ["app/uninstalled"]

  # Handled by: /app/routes/webhooks.app.scopes_update.tsx
  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  # Webhooks can have filters
  # Only receive webhooks for product updates with a product price >= 10.00
  # See: https://shopify.dev/docs/apps/build/webhooks/customize/filters
  # [[webhooks.subscriptions]]
  # topics = ["products/update"]
  # uri = "/webhooks/products/update"
  # filter = "variants.price:>=10.00"

  # Mandatory compliance topic for public apps only
  # See: https://shopify.dev/docs/apps/build/privacy-law-compliance
  # [[webhooks.subscriptions]]
  # uri = "/webhooks/customers/data_request"
  # compliance_topics = ["customers/data_request"]

  # [[webhooks.subscriptions]]
  # uri = "/webhooks/customers/redact"
  # compliance_topics = ["customers/redact"]

  # [[webhooks.subscriptions]]
  # uri = "/webhooks/shop/redact"
  # compliance_topics = ["shop/redact"]
